application: pendingworx
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /journal
  static_dir: journal

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: main.application
  
- url: /.*
  script: main.application
  login: required


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
